# Site settings
username: pandapeng
title: Pan Dapeng's Blog
email: pandapeng@outlook.com
description: "Hosted by Github"
baseurl: ""
url: ""

# Build settings
#markdown: kramdown
permalink: pretty

# Github Flavored Markdown
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

theme: jekyll-theme-cayman
